### ISSUE TITLE
Paquetages archivés ou absents de CRAN

### ISSUE THREAD

**Issue by vigou3** [dutangc/CTVproposal#1]
J'ai supprimé les paquetages archivés de la TV. Il reste ces cas:

```
1: Dans pkg("lemur") : package 'lemur' is not available on CRAN
2: Dans pkg("SimBEL") : package 'SimBEL' is not available on CRAN
3: Dans pkg("CASdatasets") : package 'CASdatasets' is not available on CRAN
4: Dans pkg("CASdatasets") : package 'CASdatasets' is not available on CRAN
```

**lemur** est considéré en phase alpha par son auteur. Je ne l'inclurais pas dans la TV, même si ça semble du travail sérieux.

**SimBEL** n'est pas publié sur CRAN. Pour moi, c'est un *no go*.

Pour ce qui **CASDatasets**, c'est clairement indiqué que le paquetage n'est pas sur CRAN, donc ça va. Cependant, je lui ai enlevé la «cote» `core`.

Enfin, **MortalityLaws** est présentement [archivé par CRAN](https://cran.r-project.org/package=MortalityLaws) pour «multiples violations de la polique». Il va falloir y garder un œil.

**Comment by dutangc** [comment]
J'ai basculé `lemur`, `SimBEL` et `CASdatasets` sur les pages github avec la fonction du même nom.  `CASdatasets` est trop volumineux pour être sur le CRAN. Les paquetages n'apparaissent pas dans la liste des paquetages CRAN mais en dessous. J'ai enlevé `MortalityLaws` puisqu'archivé.
