### ISSUE TITLE
Références bibliographiques

### ISSUE THREAD

**Issue by vigou3** [dutangc/CTVproposal#2]
J'ai placé toutes les références bibliographiques dans la section Links. Cependant, le format de celle-ci est imposé par `ctv2html` et ça ne fonctionne pas du tout.

Maintenir une bibliographie est un autre projet en soi. Je retirerais toutes les références de la TV.

La section Miscellaneous | Documentation and on-line courses pourrait devenir la section Links.

**Comment by dutangc** [comment]
Je préfère garder les références que je trouve fort utile pour les lecteurs débutants comme pour les confirmés. Éventuellement on peut enlever certaines références trop anciennes. 

D'autre TV font de même, e.g. https://cran.r-project.org/web/views/Econometrics.html, https://cran.r-project.org/web/views/DifferentialEquations.html, mais notre section est plus claire que https://cran.r-project.org/web/views/ExperimentalDesign.html par exemple.

**Comment by vigou3** [comment]
Achim a proposé de placer les références bibliographiques sous Links, comme dans la TV Econometrics. Le format est alors imposé et c'est pourquoi il a ajouté «Book», «Course» au début des entrées. Comme nous n'avons que des livres, ça devient un format inintéressant.

Comme tu as déniché des exemples de TV avec une liste de références «classiques», nous pourrions faire de même et convaincre les responsable que c'est la bonne façon de faire. ;-) Dans ce cas, un titre de section approprié serait «Bibliography» ou «References on actuarial science».

**Comment by dutangc** [comment]
Titre changé.

**Comment by dutangc** [comment]
Titre changé.
