### ISSUE TITLE
Add 'Delaporte' distribution?

### ISSUE THREAD

**Issue by zeileis** [dutangc/CTVproposal#3]
Avraham Adler @aadler responded to my announcement of the `ActuarialScience` task view on X/Twitter and suggested to include the [Delaporte](https://CRAN.R-project.org/package=Delaporte) and [revss](https://CRAN.R-project.org/package=revss) packages:

> Avraham Adler (<https://twitter.com/AvrahamAdler/status/1698608482801361206>):
> 
> Delaporte was written by me specifically for non-life actuarial work.
> 
> The genesis of revss was also actuarial work I was performing where there were fewer than 8 observations—classic in non-life excess of loss annual loss ratio analyses—needingrobust measures of location/scale.

My impression:

- `Delaporte` is already listed in the `Distributions` task view but maybe the distribution fulfills the criterion that it is of specific interest to actuarial science?
- `revss` is already listed in the `Robust` task view and my impression is that this is already sufficient, even if it has applications in actuarial science. But maybe you can have a closer look at that as well?

**Comment by aadler** [comment]
Hi. For bona fides—if it matters—I've been employed as a non-life actuary for the past 20+ years; am an FCAS, CSPA, CERA, and MAAA; have been published multiple times in [Variance](https://www.casact.org/variance-journal); and have served as CAS VP R&D for three years.

The [Delaporte](https://en.wikipedia.org/wiki/Delaporte_distribution) distribution was promulgated, and is named after, the non-life actuary Pierre J. Delaporte, who (re)introduced it to actuarial science in his 1960 paper _"Quelques problèmes de statistiques mathématiques poses par l'Assurance Automobile et le Bonus pour non sinistre" [Some problems of mathematical statistics as related to automobile insurance and no-claims bonus]_. I wrote the [`Delaporte` package](https://cran.r-project.org/package=Delaporte) after having to code the distribution in VBA for a client many years ago. The double-summation necessary made porting it to a compiled language obvious,.

As for [`revss`](https://cran.r-project.org/package=revss), the genesis was actuarial work. Both for simple high-excess loss ratio estimation and also for ranking limited observations by coverting them into "robust" Z-scores given a dearth of data. The methods of [Rousseeuw & Verboven (2001)](https://www.sciencedirect.com/science/article/abs/pii/S0167947302000786) fit nicely into the need. However, the methods themselves are not distinctly actuarial, so this one is not as clear as Delaporte, in my opinion. Thank you.

**Comment by vigou3** [comment]
Thanks Avraham for your contribution!

I quite agree with Achim. I've added Delaporte to the Loss Modeling section via f889a1b.
