### ISSUE TITLE
Package 'OpVaR' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [dutangc/CTVproposal#4]
Package [OpVaR](https://CRAN.R-project.org/package=OpVaR) is currently listed in CRAN Task View [ActuarialScience](https://CRAN.R-project.org/view=ActuarialScience) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by vigou3** [comment]
Thanks Kurt for the heads up. I've had a quick look at the package and it appears to be fairly low quality code: the whole thing is undocumented. I would just remove the package from the Task View. I'll just wait for the opinion of @dutangc.

**Comment by dutangc** [comment]
Indeed, the package is badly documented and the code is perfectible. @vigou3  you can remove the package from the CTV.

**Comment by vigou3** [comment]
Done.
